# Change these first
owner: the-bwc # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: the-bwc.com
    url: https://the-bwc.com
  - name: vb5.the-bwc.com
    url: https://vb5.the-bwc.com
  - name: discord.the-bwc.com
    url: https://discord.the-bwc.com
  - name: the-bwc.com - IPv6
    url: https://the-bwc.com
    ipv6: true
  - name: vb5.the-bwc.com - IPv6
    url: https://vb5.the-bwc.com
    ipv6: true
  - name: discord.the-bwc.com - IPv6
    url: https://discord.the-bwc.com
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.the-bwc.com
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Upptime Repo
      href: https://github.com/upptime/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - PatrickPedersen
